version: '3.6'
services:
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-alpha20
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
  caddy:
    image: caddy
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
    - "graphql-engine"
    restart: always
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./Caddyfile:/etc/Caddyfile
    - caddy_certs:/root/.caddy
volumes:
  db_data:
  caddy_certs:
