version: '3.6'
services:
  postgres:
    image: postgres:10.5
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:pull550-89a94f4
    restart: always
    depends_on:
    - "postgres"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
  caddy:
    image: caddy
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HGE_HOSTNAME: serverless-demo.hasura.app
        PAY_ALL_URL: https://us-central1-hasura-serverless.cloudfunctions.net/pay_all
        MAKE_PAYMENT_URL: https://us-central1-hasura-serverless.cloudfunctions.net/make_payment
        ORDER_APP_URL: https://serverless-demo.hasura.app/order-app/
        ANALYTICS_APP_URL: https://serverless-demo.hasura.app/analytics-app/
    depends_on:
    - "graphql-engine"
    restart: always
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./Caddyfile:/etc/Caddyfile
    - caddy_certs:/root/.caddy
volumes:
  db_data:
  caddy_certs:
