apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurnt-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-client
  template:
    metadata:
      labels:
        app: restaurant-client
    spec:
      containers:
      - name: client
        image: tirumarai/swiggy-restaurant-client

